name: Greetings

on:
  issues:
  pull_request_target:
  watch:  # triggers on star

jobs:
  greet-first-interaction:
    if: github.event_name == 'issues' || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome, and thank you for opening your first issue! We're excited to have you here."
          pr-message: "🎉 Thank you for your first pull request! Your contributions to our documentation mean a lot."

  greet-on-star:
    if: github.event_name == 'watch' && github.event.action == 'started'
    runs-on: ubuntu-latest
    steps:
      - name: Greet new stargazer
        run: |
          echo "Thank you @${{ github.actor }} for starring the repo! 🌟 We appreciate your interest in our documentation project!"
