name: Update View Count Badge

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:    # allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repository traffic
        uses: peter-evans/repository-dispatch@v2
        id: traffic
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Call GitHub API to get traffic
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/traffic/views \
               > traffic.json

      - name: Extract view count and update SVG
        run: |
          VIEWS=$(jq '.count' traffic.json)
          sed "s/{{VIEWS}}/$VIEWS/" .github/views/views.svg > views.svg

      - name: Commit updated badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add views.svg
          git commit -m "Update view count badge" || echo "No changes to commit"
          git push
